server:
  port: 8003
spring:
  application:
    name: service_vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
# endpoint 地域节点名
# accessKeyId id
# accessKdySecret 秘钥
aliyun:
  vod:
    accessKeyId: LTAI4FjU1B1fKiqWHKJPc19q
    accessKeySecret: OxUQSJNNS5QMX4Bl7jwXrMJdU0WIOt
