server:
  port: 8006
spring:
  application:
    name: service-ucenter
  profiles:
    active: dev
  # 配置数据库连接池
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-8vb8moz10j8l608c7ho.mysql.zhangbei.rds.aliyuncs.com/elon_edu?serverTimezone=GMT%2B8
      username: mac_mysql
      password: mysql2020
  #配置nacos地址
  cloud:
      nacos:
        discovery:
          server-addr: 192.168.43.145:8848
  # 配置jackson返回时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 配置redis连接池
  redis:
        host: 192.168.43.145
        port: 6379
        database: 0
        lettuce:
          pool:
            max-active: 1000
            max-idle: 32
# 指定映射文件地址
mybatis-plus:
  mapper-locations: classpath:com/zsy/ucenter/mapper/xml/*.xml

# 远程调用
feign:
  hystrix:
    enabled: true
